FROM ubuntu:22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ca-certificates file git make patch xz-utils zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
